# Generated by Django 2.2.16 on 2022-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220402_1650'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniqeu_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
    ]
